# Generated by Django 3.0.5 on 2020-04-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodorolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PomdoroList',
            new_name='PomodoroList',
        ),
    ]
